### ISSUE TITLE
Create a Build Battle Map 

### ISSUE THREAD

**Issue by webwizart** [minecraft-family/Project#19]
One of my personal favorites  are the Build Battles from Hypixel, I have the map already somewhere but it does not work yet. [Minecraft Hypixel BuildBattle Map.zip](https://github.com/minecraft-family/Project/files/294231/Minecraft.Hypixel.BuildBattle.Map.zip)

<img width="825" alt="screen shot 2016-06-01 at 21 38 31" src="https://cloud.githubusercontent.com/assets/527613/15723112/3a0bc774-2841-11e6-8d29-5ed8fba3c6ca.png">
<img width="880" alt="screen shot 2016-06-01 at 21 38 19" src="https://cloud.githubusercontent.com/assets/527613/15723115/3a0e08f4-2841-11e6-94ec-210d49e12811.png">
<img width="871" alt="screen shot 2016-06-01 at 21 37 42" src="https://cloud.githubusercontent.com/assets/527613/15723113/3a0c249e-2841-11e6-9ecf-e33b0d615a10.png">
<img width="870" alt="screen shot 2016-06-01 at 21 36 50" src="https://cloud.githubusercontent.com/assets/527613/15723111/3a092226-2841-11e6-9d85-683bfb79888a.png">

**Comment by Zorth** [comment]
building game plugin is incompatible with multiverse

**Comment by webwizart** [comment]
:-(

**Comment by webwizart** [comment]
Can we wire to separate servers? we could host our current one and one on the side for build battles. But only if we can go from one server to another without the hassle of switching servers on the client.

**Comment by Zorth** [comment]
Edit: Server has BuildBattle minigame (max 36 persons, min 2). Themes are still to be added with /bbadmin addtopic (topic)

**Comment by webwizart** [comment]
Nice, is it a seperate world? 
So an admin must be around to let them play or can you pass in an array of topics?
