### ISSUE TITLE
Replace Vanilla server with Spigot

### ISSUE THREAD

**Issue by webwizart** [minecraft-family/Project#4]
Replace the server at MCHosting which is a vanilla server with a Spigot server.
This allows us to  install mods and improve the management of the server.

**Comment by bgotink** [comment]
We'd need to make sure we only use vanilla mods (i.e. mods that run server-side and don't require any mods client-side)

If we ever want to start using mods that require client changes as well (e.g. computercraft), we can look into that later.

**Comment by webwizart** [comment]
True I made a ticket per mod so far it`s
- bad words
- griefprevention - question should we prevent this or teach kids not to do that and ban if they do
- multiverse

**Comment by Zorth** [comment]
completed :smile:

**Comment by webwizart** [comment]
You can close the issue if you are convinced that it 's done, and add a final comment telling what you did to close the ticket.
