### ISSUE TITLE
Make the chat log viewable.

### ISSUE THREAD

**Issue by webwizart** [minecraft-family/Project#8]
It would be nice to be able to see the server chat log on the website.Or even filter it by name or time.

**Comment by bgotink** [comment]
Some open questions:
- do we show this real-time?
  - if real-time, do we show updates real-time as well on the website or will we require a refresh?
  - if real-time, do we allow interacting from the site as well? e.g. allow reading & replying but disallow server commands from chat
  - if real-time and we're allowing interaction, investigate whether it'd be possible to link this to telegram or hangouts, i.e. to have a group chat which is linked to the MC server and which can be accessed on any device (phone, tablet, pc). This allows for notifications (on new messages, perhaps even on mentions if we get that right)
- in case of delay: how much?

**Comment by webwizart** [comment]
- it would be nice to see it in realtime.
  - do we allow interaction from the site? This is interesting, what do you mean? 
    - Do you allow every random guest to reply to all?
    - Can everybody who is signed in reply to all?
    - Or can signed in parents read all comments and only talk to their own kids? I prefer this option most.
  - about interaction
    - would this be public? 
    - or is this only for members
    - or is this only for server managers, if so I already have an app to manage the server remote. MConsole https://play.google.com/store/apps/details?id=pl.skifo.mconsole&hl=en  It works with RCON. 
      I would prefer our own web based management app on the website. but for now it works well. But it's something we can give to the parents in the future.

**Comment by webwizart** [comment]
double checking the app I see it does not keep history of the chat.
